apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dpsrv
  name: neo4j-dev-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dpsrv
  name: neo4j-prod-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
